{% set name = "sahi" %}
{% set version = "0.8.19" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sahi-{{ version }}.tar.gz
  sha256: c7422a83f524f996191e11f2b7d0624caddfb5e8b24eb5cacd72ec373ef4d194

build:
  number: 0
  noarch: python
  entry_points:
    - sahi=sahi.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - fire
    - py-opencv >=4.2.0.32
    - pillow >=8.2.0
    - python >=3.7
    - pyyaml
    - shapely >=1.8.0
    - terminaltables
    - tqdm >=4.48.2
    - requests
    - pytorch

test:
  imports:
    - sahi
    - sahi.postprocess
  commands:
    # - pip check
    - sahi --help
  # requires:
  #  - pip

about:
  home: https://github.com/obss/sahi
  summary: A vision library for performing sliced inference on large images/small objects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fcakyon
    - weiji14
