{% set name = "sahi" %}
{% set version = "0.11.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sahi-{{ version }}.tar.gz
  sha256: b9b483e7adf4e7a2d9ad95e787a90ac62e7e391b0dcd4585014031820eadda7d

build:
  number: 0
  noarch: python
  entry_points:
    - sahi=sahi.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - fire
    - py-opencv >=4.2.0.32
    - pillow >=8.2.0
    - python >=3.6
    - pyyaml
    - shapely >=1.8.0
    - terminaltables
    - tqdm >=4.48.2
    - requests
    - pytorch
    - pybboxes ==0.1.4

test:
  imports:
    - sahi
    - sahi.postprocess
  commands:
    # - pip check
    - sahi --help
  # requires:
  #  - pip

about:
  home: https://github.com/obss/sahi
  summary: A vision library for performing sliced inference on large images/small objects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fcakyon
    - weiji14
