{% set name = "sahi" %}
{% set version = "0.11.30" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sahi-{{ version }}.tar.gz
  sha256: f586085a8ee49ce5726d93aaa4d1fd77ff5eeee575a77c1d567ec17d17842b0c

build:
  number: 0
  noarch: python
  entry_points:
    - sahi=sahi.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - opencv <=4.11.0.86
    - click
    - fire
    - pillow >=8.2.0
    - py-opencv <=4.11.0.86
    - pybboxes ==0.1.6
    - python >={{ python_min }}
    - pytorch
    - pyyaml
    - requests
    - shapely >=2.0.0
    - terminaltables
    - tqdm >=4.48.2

test:
  imports:
    - sahi
    - sahi.postprocess
  commands:
    - pip check
    - sahi --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/obss/sahi
  summary: A vision library for performing sliced inference on large images/small objects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fcakyon
    - weiji14
