schema_version: 1

context:
  name: sahi
  version: 0.12.8
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sahi-${{ version }}.tar.gz
  sha256: f2074b3b3aa0f655dbdd69fbb1f1a0b985220f5fb3d920a4206eba160d37028a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - sahi=sahi.cli:app

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
  run:
    - click
    - fire
    - matplotlib-base
    - numpy
    - pillow >=8.2.0
    - py-opencv >=4.12.0.88
    - python >=${{ python_min }}
    - pyyaml
    - requests
    - shapely >=2.0.0
    - tqdm >=4.48.2
    # IMPORTANT: please use py-opencv, not opencv, see
    # https://github.com/conda-forge/sahi-feedstock/pull/58#discussion_r1674766023
tests:
  - python:
      imports:
        - sahi
        - sahi.annotation
        - sahi.auto_model
        - sahi.postprocess
        - sahi.prediction
        - sahi.models.base
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - sahi --help
      - sahi coco --help
      - sahi version

about:
  homepage: https://obss.github.io/sahi/
  repository: https://github.com/obss/sahi
  summary: A vision library for performing sliced inference on large images/small objects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - onuralpszr
    - fcakyon
    - weiji14
