schema_version: 1

context:
  name: sahi
  version: 0.12.5
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sahi-${{ version }}.tar.gz
  sha256: 3a01ab9c639393be8da546b03ca512a45eee2222d2552043db6cc50c7e66eaac

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - sahi=sahi.cli:app

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
  run:
    - click
    - fire
    - matplotlib-base
    - numpy
    - pillow >=8.2.0
    - python >=${{ python_min }}
    - pyyaml
    - requests
    - shapely >=2.0.0
    - tqdm >=4.48.2
    - opencv >=4.12.0.88
tests:
  - python:
      imports:
        - sahi
        - sahi.postprocess
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - sahi --help
      - sahi coco --help
      - sahi version

about:
  homepage: https://obss.github.io/sahi/
  repository: https://github.com/obss/sahi
  summary: A vision library for performing sliced inference on large images/small objects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - onuralpszr
    - fcakyon
    - weiji14
